console.log("Addition: 10 + 10 = " + (10 + 10));
console.log("Subtration: 20 - 10 = " + (20 - 10));
console.log("Multiplication: 10 * 20 = " + (10 * 20));
console.log("Division: 20 / 10 = " + (20 / 10));
console.log("Modulation: 55 % 10 = " + (55 % 10));
var A = 10;
console.log("A = " + A + "then");
var B = ++A;
console.log("A++ (Increment operator) : " + B);
var C = --A;
console.log("A-- (Decrenemt operator) : " + C);
