console.log("Logical operator....");
console.log("They are use to compile two or more condition");
console.log("It returns only true and false value");
console.log("&& (and) -> The operator returns true only if all the expressions specified return true ");
console.log("|| (or) -> The operator returns true if at least one of the expressions specified return true ");
console.log("! (not) -> The operator returns the inverse of the expression’s result");
console.log();
console.log(" 0 = false , 1 = true ");
console.log();
console.log(" And operator ");
console.log(true && false);
console.log(true && true);
console.log(false && false);
console.log();
console.log(" OR operator ");
console.log(true || true);
console.log(true || false);
console.log(false || false);
console.log();
console.log(" Not operator ");
console.log(" not 0 : " + !false);
console.log(" not 1 : " + !true);
